### ISSUE TITLE
Error when starting Postgres container

### ISSUE THREAD

**Issue by jakubkarczewski** [data-max-hq/dbt-streamlit-covid-analytics#5]
Hey!

When running ` docker compose up postgres` I get an error:

```
ERROR: Service 'streamlit' depends on service 'db' which is undefined.
```

Do I need to add something to `docker-compose.yaml` to get it working?

**Comment by ArbinBici** [comment]
Hey!

Although I do not think ```docker compose up postgres``` should run the streamlit service, you could try this:

In ```docker-compose.yaml```
```Dockerfile
services:
  streamlit:
    build: .
    extra_hosts:
    - "host.docker.internal:host-gateway"
    ports:
      - "8501:8501"
    volumes:
      - streamlit:/data/streamlit
    depends_on:
      - db
```

Change the last two rows to:
```Dockerfile
    depends_on:
      - postgres
```
